// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtH2MW_ZHpIuFvso_EXK9ZTvQOemVL-6w',
    appId: '1:646839209745:web:483046830baa7d1ada06b0',
    messagingSenderId: '646839209745',
    projectId: 'bantaynuevo',
    authDomain: 'bantaynuevo.firebaseapp.com',
    storageBucket: 'bantaynuevo.firebasestorage.app',
    measurementId: 'G-KT5CP7QWXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoZve28I1_6EDz3l8XcAPo2sQOFre33So',
    appId: '1:646839209745:android:e44a4475275d5ff4da06b0',
    messagingSenderId: '646839209745',
    projectId: 'bantaynuevo',
    storageBucket: 'bantaynuevo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvdtJV4oOycA29k-VP-wqPLi5hebdS7LY',
    appId: '1:646839209745:ios:ce9ee61ace55ce22da06b0',
    messagingSenderId: '646839209745',
    projectId: 'bantaynuevo',
    storageBucket: 'bantaynuevo.firebasestorage.app',
    iosBundleId: 'com.baranggaycaminonuevo.bantayNuevo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvdtJV4oOycA29k-VP-wqPLi5hebdS7LY',
    appId: '1:646839209745:ios:ce9ee61ace55ce22da06b0',
    messagingSenderId: '646839209745',
    projectId: 'bantaynuevo',
    storageBucket: 'bantaynuevo.firebasestorage.app',
    iosBundleId: 'com.baranggaycaminonuevo.bantayNuevo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtH2MW_ZHpIuFvso_EXK9ZTvQOemVL-6w',
    appId: '1:646839209745:web:4fac9fbc3ec2ae93da06b0',
    messagingSenderId: '646839209745',
    projectId: 'bantaynuevo',
    authDomain: 'bantaynuevo.firebaseapp.com',
    storageBucket: 'bantaynuevo.firebasestorage.app',
    measurementId: 'G-XLRZYTWMT2',
  );
}
