import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../../../models/report_model.dart';

/// Builds a printable/shareable PDF for a single incident report — the
/// "Generate Reports" capability from the thesis's Barangay Official
/// functional requirements (§3.2.1 / §3.4), which had no implementation
/// anywhere in the app before this.
///
/// Deliberately does NOT embed the actual evidence files (photos, videos,
/// audio) — only lists their names/types/upload dates. Report review
/// screens already tell tanod "files are encrypted and locked to this
/// case... can't be downloaded" specifically to preserve the evidence
/// chain of custody; a PDF export that re-packaged the evidence content
/// itself would undermine that same protection through a side door. This
/// document is the official case summary, not an evidence bundle.
class ReportPdfGenerator {
  ReportPdfGenerator._();

  static Future<pw.Document> generate({
    required ReportModel report,
    required String residentName,
    String? assignedResponderName,
    required String generatedByName,
  }) async {
    final doc = pw.Document();

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.letter,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('BARANGAY CAMINO NUEVO', style: pw.TextStyle(fontSize: 10, letterSpacing: 1.2)),
            pw.SizedBox(height: 2),
            pw.Text('Incident Report', style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 2),
            pw.Text('Case ID: ${report.id}', style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700)),
            pw.Divider(height: 24),

            _row('Incident Type', report.type),
            _row('Status', report.status.displayLabel),
            _row('Filed By', residentName),
            _row('Date Filed', _formatDate(report.createdAt)),
            if (assignedResponderName != null) _row('Assigned To', assignedResponderName),
            if (report.locationAddress != null) _row('Location', report.locationAddress!),
            if (report.lat != null && report.lng != null)
              _row('Coordinates', '${report.lat!.toStringAsFixed(6)}, ${report.lng!.toStringAsFixed(6)}'),

            pw.SizedBox(height: 16),
            pw.Text('DESCRIPTION', style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, letterSpacing: 0.8)),
            pw.SizedBox(height: 6),
            pw.Text(report.description, style: const pw.TextStyle(fontSize: 11)),

            pw.SizedBox(height: 16),
            pw.Text('EVIDENCE ON FILE', style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, letterSpacing: 0.8)),
            pw.SizedBox(height: 6),
            if (report.evidenceFiles.isEmpty)
              pw.Text('No evidence uploaded.', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700))
            else
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
                columnWidths: const {0: pw.FlexColumnWidth(3), 1: pw.FlexColumnWidth(1.2), 2: pw.FlexColumnWidth(1.5)},
                children: [
                  _tableHeaderRow(['File name', 'Type', 'Uploaded']),
                  for (final file in report.evidenceFiles)
                    _tableRow([file.name, file.type, _formatDate(file.uploadedAt)]),
                ],
              ),
            pw.SizedBox(height: 4),
            pw.Text(
              'Evidence file contents are not included in this document — files remain locked to the '
              'in-app evidence vault to preserve chain of custody. This report lists file metadata only.',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600, fontStyle: pw.FontStyle.italic),
            ),

            pw.SizedBox(height: 16),
            pw.Text('ACCESS LOG', style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, letterSpacing: 0.8)),
            pw.SizedBox(height: 6),
            if (report.accessLog.isEmpty)
              pw.Text('No access recorded.', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700))
            else
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
                columnWidths: const {0: pw.FlexColumnWidth(2), 1: pw.FlexColumnWidth(1.5)},
                children: [
                  _tableHeaderRow(['Accessed by', 'Date/time']),
                  for (final entry in report.accessLog) _tableRow([entry.who, _formatDate(entry.when)]),
                ],
              ),

            pw.Spacer(),
            pw.Divider(),
            pw.Text(
              'Generated by $generatedByName on ${_formatDate(DateTime.now())} via Bantay Nuevo. '
              'This is a system-generated summary for barangay records and is not a certified legal document.',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
            ),
          ],
        ),
      ),
    );

    return doc;
  }

  static pw.Widget _row(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(width: 110, child: pw.Text(label, style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700))),
          pw.Expanded(child: pw.Text(value, style: const pw.TextStyle(fontSize: 10))),
        ],
      ),
    );
  }

  static pw.TableRow _tableHeaderRow(List<String> labels) {
    return pw.TableRow(
      decoration: const pw.BoxDecoration(color: PdfColors.grey200),
      children: [
        for (final label in labels)
          pw.Padding(
            padding: const pw.EdgeInsets.all(5),
            child: pw.Text(label, style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold)),
          ),
      ],
    );
  }

  static pw.TableRow _tableRow(List<String> cells) {
    return pw.TableRow(
      children: [
        for (final cell in cells)
          pw.Padding(padding: const pw.EdgeInsets.all(5), child: pw.Text(cell, style: const pw.TextStyle(fontSize: 9))),
      ],
    );
  }

  static String _formatDate(DateTime? date) {
    if (date == null) return '—';
    final d = date;
    String two(int n) => n.toString().padLeft(2, '0');
    return '${d.year}-${two(d.month)}-${two(d.day)} ${two(d.hour)}:${two(d.minute)}';
  }
}
